# Knumpy - Kotlin Binding for Numpy

In [1]:
%use numpy

In [2]:
val a = arange(15).reshape(3, 5)

In [3]:
println(a.shape.contentEquals(intArrayOf(3, 5)))
println(a.ndim == 2)
println(a.dtype)

true
true
class java.lang.Integer


## create an array of ints, we square each element and the shape to (3, 5)

In [4]:
val b = (arange(15) `**` 2).reshape(3, 5)

In [5]:
println(b)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


## Kotlin is statically typed language

In [14]:
import org.jetbrains.numkt.random.Random

val c = ones<Int>(3, 3) * 3
val d = Random.random(3, 3)

In [18]:
println(d * c)

[[0.67715439 0.57855042 2.42457032]
 [0.1001215  0.93752581 1.26676908]
 [2.48473226 2.94009942 2.4423432 ]]


In [19]:
println(c * d)

[[0.67715439 0.57855042 2.42457032]
 [0.1001215  0.93752581 1.26676908]
 [2.48473226 2.94009942 2.4423432 ]]
